---
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --cri-socket=unix:///var/run/crio/crio.sock --apiserver-advertise-address={{ k8s_api_ip }} --node-name {{ servername }} --apiserver-cert-extra-sans={{ k8s_api_ip }}  >> cluster_initialized.txt
