apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: storage-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./provisioners/flux/infrastructure/networking
  prune: true
