---
version: "3"
vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provisioners/ansible"
  REMOTE_USER: 
    sh: "whoami"
includes:
  ansible: .taskfiles/ansible.yaml