apiVersion: v1
data:
  api-token: SGdnaUwyY09jUmRNRDhqTDh2RGt3SWJPVzVTTkdraWhjLWROSlRUMw==
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: networking
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-stg
spec:
  acme:
    email: scuffe82@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-stg
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token
          email: scuffe82@gmail.com
status:
  acme:
    lastRegisteredEmail: scuffe82@gmail.com
    uri: https://acme-staging-v02.api.letsencrypt.org/acme/acct/50523518
  conditions:
  - lastTransitionTime: "2022-04-12T00:01:13Z"
    message: The ACME account was registered with the ACME server
    observedGeneration: 1
    reason: ACMEAccountRegistered
    status: "True"
    type: Ready