apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
  - https://github.com/metallb/metallb/blob/main/charts/metallb/charts/crds/templates/crds.yaml
  - crd-prometheusrules.yaml
  - crd-servicemonitors.yaml
  - crd-traefikMiddleware.yaml