---

- hosts:
    - masters
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - k8s_install/master

#- hosts:
#    - workers
#  become: true
#  gather_facts: true
#  any_errors_fatal: true
#  roles:
#    - k8s_install/worker

#- hosts:
#    - 127.0.0.1
#  become: false
#  any_errors_fatal: true
#  connection: local
#  roles:
#    - k8s_install/flux_prep