apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/nginx-app/release.yaml
patchesStrategicMerge:
  - helm-vaules-patch.yaml
configMapGenerator:
  - name: nginx-app-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml