apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tigera-operator
resources:
  - namespace.yaml
  - ebpf.yaml
  - release.yaml
configMapGenerator:
  - name: calico-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
patches:
  - patch: |-
     '{
        "spec": {
          "template": {
            "spec": {
              "nodeSelector": {
                "non-calico": "true"
              }
            }
          }
        }
      }'     
    target:
      kind: DaemonSet
      labelSelector: "k8s-app=kube-proxy"