apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - namespace.yaml
  - client-info.yaml
  - release.yaml
configMapGenerator:
  - name: synology-csi-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml