apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postconfigs
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: networking-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./provisioners/flux/infrastructure/postconfigs
  prune: true
  validation: client
  decryption:            
    provider: sops       
    secretRef:           
      name: sops-age 