apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: storage-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: core-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./provisioners/flux/infrastructure/storage
  prune: true
  validation: client
  decryption:            
    provider: sops       
    secretRef:           
      name: sops-age 