# Source: traefik-forward-auth/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-2.1.2
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 4181
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: traefik-forward-auth
---
# Source: traefik-forward-auth/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-2.1.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-forward-auth
      app.kubernetes.io/instance: traefik-forward-auth
  template:
    metadata:
      
      labels:
        app.kubernetes.io/name: traefik-forward-auth
        app.kubernetes.io/instance: traefik-forward-auth
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: traefik-forward-auth
          image: "thomseddon/traefik-forward-auth:2.2.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: "AUTH_HOST"
              value: "auth.spenceops.com"
            - name: "COOKIE_DOMAIN"
              value: "spenceops.com"
            - name: "DEFAULT_ACTION"
              value: "auth"
            - name: "DEFAULT_PROVIDER"
              value: "google"
            - name: "DOMAIN"
              value: "spenceops.com, gmail.com"
            - name: "LOG_LEVEL"
              value: "error"
            - name: "PROVIDERS_GOOGLE_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key: PROVIDERS_GOOGLE_CLIENT_ID
                  name: traefik-forward-auth-secret
            - name: "PROVIDERS_GOOGLE_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key: PROVIDERS_GOOGLE_CLIENT_SECRET
                  name: traefik-forward-auth-secret
            - name: "SECRET"
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: traefik-forward-auth
            - name: "TZ"
              value: "America/Denver"
            - name: "WHITELIST"
              valueFrom:
                secretKeyRef:
                  key: WHITELIST
                  name: traefik-forward-auth-secret
          ports:
            - name: http
              containerPort: 4181
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 4181
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
---
# Source: traefik-forward-auth/templates/middleware.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: "http://traefik-forward-auth.networking:4181"
    authResponseHeaders:
      - X-Forwarded-User
