apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - namespace.yaml
  - release.yaml
  - ipaddresspool.yaml
configMapGenerator:
  - name: metallb-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml