configInline:
  address-pools:
      - name: manual
        protocol: layer2
        addresses:
        - 10.0.0.220-10.0.0.229
      - name: automatic
        protocol: layer2
        addresses:
        - 10.0.0.230-10.0.0.239
prometheusRule:
  enabled: true

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    
speaker:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true