---
- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Update /etc/hosts to include hostname
  ansible.builtin.blockinfile:
    path: /etc/hosts
    create: true
    block: |
      127.0.0.1 localhost
      127.0.1.1 {{ inventory_hostname }}

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

- name: Set Kubernetes network configuration
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 0644
    create: true
    block: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv6.conf.all.forwarding = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: load required modules
  modprobe: 
    name: "{{ item }}"
    state: present
  with_items:
  - overlay
  - br_netfilter

- name: Reload Kubernetes network configuration
  ansible.builtin.shell: sysctl -p /etc/sysctl.d/99-kubernetes-cri.conf

- name: enable jumbo frames for netplan
  lineinfile:
    path: /etc/netplan/00-installer-config.yaml
    insertbefore: 'nameservers:'
    line: "\ \ \ \ \ \ mtu: 9000"
    state: present  

- name: apply netplan
  shell: netplan generate && netplan apply
  become: true

- name: Remove old resolv.conf link
  file:
    path: /etc/resolv.conf
    state: absent

- name: link real resolv.conf to /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: presist modules
  lineinfile:
    path: /etc/modules
    line: "{{ item }}"
  with_items:
  - overlay
  - br_netfilter

