apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: networking
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
  interval: 5m0s
  releaseName: authentik