apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: staticpool
  namespace: networking
spec:
  addresses:
  - 10.0.0.200-10.0.0.2.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: networking