apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - release.yaml
  - storage-class-temp.yaml
configMapGenerator:
  - name: nfs-sub-dir-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml